# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Create Volume
        run: mkdir -p ${GITHUB_WORKSPACE}/public
      - name: Run Docker Container
        run: |
          docker pull iotcat/latex
          docker run --name latex-container -v ${GITHUB_WORKSPACE}:/tmp iotcat/latex /bin/sh -c "latexmk -outdir=/tmp -pdf /tmp/resume.tex"
      - name: Move generated pdf to the public directory
        run:  mv ${GITHUB_WORKSPACE}/resume.pdf ${GITHUB_WORKSPACE}/public/
      - name: List contents of public directory
        run: ls -l ${GITHUB_WORKSPACE}/public
      - name: List contents of directory
        run: ls -l
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: './public'

  commit:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dist
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: public
      - name: List contents of directory
        run: ls -l
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ref to ${{ github.sha }}"


  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pages: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: public
      - name: List contents of directory
        run: ls -l
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload Page artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
